name: Release Binaries

on:
  push:
    tags:
      - '*'

jobs:

  build:
    uses: ./.github/workflows/build.yml

  release:
    name: Release
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      packages: 'write'
      pull-requests: 'read'

    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          path: firmware

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            firmware/**/*.uf2
